<?php

namespace AppBundle\Repository;

/**
 * role_utilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class role_utilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
